### ISSUE TITLE
Webpage address

### ISSUE THREAD

**Issue by MartinBoehm1** [htl-perg-2018-19-4bhif/angular-routing-example-MartinBoehm1#1]
http://86.56.132.143

**Comment by rstropek** [comment]
Thank you for the link. I tried to access it but I did not get a connection. Could you check?

Greetings.
Rainer Stropek.

**Comment by MartinBoehm1** [comment]
I'm sorry, I forgot to keep the Pc running thus the Server wasn't reachable yesterday. Now it's working again.

**Comment by rstropek** [comment]
Ok, now it works as expected. Thank you.

Greetings,
Rainer Stropek.
